[package]
name = "boost_signals2"
description = "Boost C++ library boost_signals2 packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_signals2"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_signals2"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_assert = { version = "0.1.0", path = "../boost_assert" }
boost_bind = { version = "0.1.0", path = "../boost_bind" }
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_core = { version = "0.1.0", path = "../boost_core" }
boost_function = { version = "0.1.0", path = "../boost_function" }
boost_iterator = { version = "0.1.0", path = "../boost_iterator" }
boost_move = { version = "0.1.0", path = "../boost_move" }
boost_mpl = { version = "0.1.0", path = "../boost_mpl" }
boost_optional = { version = "0.1.0", path = "../boost_optional" }
boost_parameter = { version = "0.1.0", path = "../boost_parameter" }
boost_preprocessor = { version = "0.1.0", path = "../boost_preprocessor" }
boost_smart_ptr = { version = "0.1.0", path = "../boost_smart_ptr" }
boost_throw_exception = { version = "0.1.0", path = "../boost_throw_exception" }
boost_tuple = { version = "0.1.0", path = "../boost_tuple" }
boost_type_traits = { version = "0.1.0", path = "../boost_type_traits" }
boost_variant = { version = "0.1.0", path = "../boost_variant" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
